# Generated by Django 3.1.4 on 2020-12-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Верный ответ'),
        ),
    ]
