# Generated by Django 3.1.4 on 2020-12-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_choice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
